[refactor] 유효성 및 나라 자동완성
prgrms-web-devcourse/Team-Moongsal-Travel.zip-FE pull request #64
Opened 2023-03-05 07:25 UTC by kmww

## ⛓ 관련 이슈

- close #56 

## 📝 작업 내용

- 여행기간
  - 여행기간 종료일은 현재 날짜 기준입니다.
  - 시작날짜가 종료날짜보다 클 수 없습니다.
- 모든 form input에 validation을 추가했습니다.
- 총 경비
  - 숫자만 입력가능
- 모든 값은 필수 입력해야함
- 방문나라를 상수화하여 자동완성 기능을 추가(246개국)
- 토글 버튼 클릭시 방문나라가 나타나도록 수정

## 📍 PR Point

- 다른 페이지와 마찬가지로 helpertext를 이용하였고 OutlinedInput의 경우 helperText 속성이 없기때문에 mui의 HelperText컴포넌트를 사용하였습니다.

## 📷 스크린샷

국내 선택시
![image](https://user-images.githubusercontent.com/105067764/222947457-6518b764-e88d-4f72-9ff8-cd0cb4eaf240.png)
해외 선택시
![image](https://user-images.githubusercontent.com/105067764/222947470-879f262a-72bf-4fe3-97c6-aeab9b6e9002.png)
입력 불충분시 helpertext
![image](https://user-images.githubusercontent.com/105067764/222947490-baa6c13f-9731-4fac-a3d8-d7c3fa583865.png)

2023-03-06 05:33 UTC, solar3070 requested changes
고생하셨습니다~

2023-03-06 05:33 UTC, solar3070 approved these changes
고생하셨습니다~

2023-03-06 05:36 UTC, solar3070 commented on src/types/post.ts
> +export interface CreatePostType {
ask;

저는 `post`보다는 저희 서비스에 더 적합한 이름인 `travelogue`를 사용하는 것을 선호하는 편인데 트래블로그와 서브 트래블로그 모두 `post` 혹은 `travelogue`로 통일하는 게 좋을 것 같습니다. 다른 두 분의 의견이 궁금합니다. @park-moen

2023-03-06 05:36 UTC, solar3070 commented on src/hooks/useTravelogueForm.ts
> +        value: /^[가-힣 ]+$/,
proposal;

`가-힣` 다음의 공백의 의도된 공백이 아니라면 지워주세요!

2023-03-06 05:36 UTC, solar3070 commented on src/components/common/CountrySelect.tsx
> +          popupIcon={<LocationOnOutlinedIcon />}
ask;

첨부하신 자동완성 사진에서 아이콘이 뒤집혀 있는데 왜 그런가요?

2023-03-06 09:03 UTC, kmww commented on src/types/post.ts
> +export interface CreatePostType {
현재 피드쪽에서도 travelogue로 사용하는것으로 알고있어서
post라고 써두었습니다 명재님의 의견도 궁금합니다

2023-03-06 09:06 UTC, kmww commented on src/hooks/useTravelogueForm.ts
> +        value: /^[가-힣 ]+$/,
의도된 공백입니다
`남아프리카 공화국` 처럼 공백이 포함된 나라도 입력하기 위해서입니다

2023-03-06 09:06 UTC, kmww commented on src/components/common/CountrySelect.tsx
> +          popupIcon={<LocationOnOutlinedIcon />}
이걸 수정을 안했네요..
팝업시 자동으로 180도로 변경되는것 같습니다.

2023-03-06 09:37 UTC, kmww commented on src/types/post.ts
> +export interface CreatePostType {
다시보니까 travelogueFeed를 사용중이네요
모든 포스트를 travelogue로 통일하는게 좋겠어요

2023-03-07 00:01 UTC, park-moen commented on src/types/post.ts
> +export interface CreatePostType {
저도 명시적으로 `travelogue`를 사용하면 좋겠다는 의견입니다. 그리고 `TravelogueFeed`는 공통으로 사용되고 있어서 `@components/common/Feed`로 공통화하면 어떨까요. 메인 페이지, 마이페이지, 특정 검색 페이지처럼 다양한 곳에서 사용되고 있어서 이런 의견을 생각해봤습니다.

2023-03-07 00:44 UTC, park-moen reviewed
고생하셨습니다.

2023-03-07 00:44 UTC, park-moen commented on src/api/post/index.ts
> +import { CreatePostType, SubTravelogue } from '@/types/post';
p1;

```suggestion
import { CreatePostType, SubTravelogueType } from '@/types/post';
```

혜준님 코드 리뷰하면서 새롭게 추간된 Type 컨벤션입니다. PR 머지 전에 반영해주세요.

[추가된 Type 컨벤션](https://github.com/prgrms-web-devcourse/Team-Moongsal-Travel.zip-FE/pull/63#discussion_r1125425422)

2023-03-07 00:44 UTC, park-moen commented on src/api/post/index.ts
> +import { CreatePostType, SubTravelogue } from '@/types/post';
혜준님이 작업한 부분이라서 혜준님이 변경해야겠네요. @solar3070

2023-03-07 00:44 UTC, park-moen commented on src/api/post/index.ts
> +export const createPost = async (data: CreatePostType) => {
proposal;

혜준님이 구현한 `postSubTravelogue` 비동기 함수와 민우님이 구현한 `createPost` 비동기 함수의 네이밍 형태가 일치하면 좋겠어요. 둘 다 post로 가져가도 좋고 create로 가져가도 좋겠네요.

2023-03-07 00:44 UTC, park-moen commented on src/components/CreatePost/ComplexButton.tsx
> +  };
p1;

```suggestion
  const onReset = (e: MouseEvent<HTMLElement>) => {
    handleChange(e, '');
  };
```


![image](https://user-images.githubusercontent.com/57402711/223285999-205abccf-e3fe-4357-a007-11502717d3be.png)

2023-03-07 00:44 UTC, park-moen commented on src/components/CreatePost/DatePicker.tsx
> +import { CreatePostType } from '@/types/post';
👍🔥 타입 컨벤션 굿!

2023-03-07 00:44 UTC, park-moen commented on src/components/common/CountrySelect.tsx
> +import { LocationOnOutlined as LocationOnOutlinedIcon } from '@mui/icons-material';
👍🔥 명확한 아이콘 컴포넌트 네이밍 굿!!

2023-03-07 00:44 UTC, park-moen commented on src/components/common/CountrySelect.tsx
> +    }
ask;

`isSelected` props는 대한민국을 클릭하면 true인가요? 만약 대한민국을 클릭한 경우가 true라면 명확한 이름으로 식별자 네이밍을 변경하면 좋겠어요.

2023-03-07 00:44 UTC, park-moen commented on src/components/common/CountrySelect.tsx
> +  }, [isSelected]);
ask;

```suggestion
  }, [isSelected, name]);
```

`useEffect` 의존성에 `name` props를 추가하지 않은 이유가 있나요?

2023-03-07 00:44 UTC, park-moen commented on src/hooks/useTravelogueForm.ts
> +const usePostForm = (control: Control<CreatePostType>) => {
ask;

파일명은 `useTravelogueForm.ts`로 만들고 컴포넌트 이름은 `usePostForm`로 만든 이유가 있나요? (파일 이름과 컴포넌트 이름을 동일하게 가져가지 않은 이유가 궁금합니다.)

2023-03-07 06:19 UTC, kmww commented on src/api/post/index.ts
> +export const createPost = async (data: CreatePostType) => {
제가 postTravelogue로 변경하겠습니다~

2023-03-07 06:32 UTC, kmww commented on src/components/CreatePost/ComplexButton.tsx
> +  };
![image](https://user-images.githubusercontent.com/105067764/223339934-c3d42783-86fc-4b04-9a3b-544274d32f14.png)

저희 이걸로 바뀌었어요...

2023-03-07 06:33 UTC, kmww commented on src/components/CreatePost/ComplexButton.tsx
> +  };
handleChange를 onChange로 바꾸어야겠네요

2023-03-07 06:36 UTC, kmww commented on src/components/common/CountrySelect.tsx
> +  }, [isSelected]);
저번에도 말씀드린것처럼 name을 주게되면, 해외를 선택후
나라를 입력할때 해당 함수가 호출되기때문에 name.onChange('')떄문에 입력이 불가능합니다

2023-03-07 06:40 UTC, kmww commented on src/components/common/CountrySelect.tsx
> +    }
확인했습니다

2023-03-07 06:44 UTC, kmww commented on src/hooks/useTravelogueForm.ts
> +const usePostForm = (control: Control<CreatePostType>) => {
원래 파일이름이 usePostForm이었고 혜준님이 구현하신 useSubTravelogueForm의 이름을 따라가려고 변경했는데
내부 변경을 깜빡한것 같습니다!
바로 수정할게요

2023-03-07 07:30 UTC, merged